version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - "6532:5432"
    environment:
      POSTGRES_DB: library_db
      POSTGRES_USER: postdb
      POSTGRES_PASSWORD: 123456

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/library_db
      SPRING_DATASOURCE_USERNAME: postdb
      SPRING_DATASOURCE_PASSWORD: 123456